# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-10-06 18:20
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodTruckApp', '0002_auto_20181006_1306'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('announcement_text', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Header',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=50)),
                ('item_description', models.CharField(max_length=100)),
                ('item_price', models.FloatField(blank=True, default=None, null=True)),
                ('header', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FoodTruckApp.Header')),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FoodTruckApp.Header')),
            ],
        ),
        migrations.CreateModel(
            name='OperationHours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')], unique=True)),
                ('from_hour', models.TimeField()),
                ('to_hour', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Profile_Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='profile_image/img_avatar2.png', upload_to='profile_image')),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('truck_name', models.CharField(max_length=50)),
                ('truck_description', models.CharField(max_length=150)),
                ('truck_phone_number', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999-999-9999'.", regex='^\\d{3}--\\d{3}--\\d{4})')])),
                ('truck_email_address', models.CharField(max_length=50)),
                ('rating', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Truck_Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FoodTruckApp.Tags')),
                ('truck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FoodTruckApp.Truck')),
            ],
        ),
        migrations.CreateModel(
            name='TruckList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(5.0)])),
                ('truck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FoodTruckApp.Truck')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FoodTruckApp.UserProfile')),
            ],
        ),
        migrations.AddField(
            model_name='operationhours',
            name='truck',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FoodTruckApp.Truck'),
        ),
        migrations.AddField(
            model_name='menu',
            name='truck',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FoodTruckApp.Truck'),
        ),
        migrations.AddField(
            model_name='announcements',
            name='truck',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FoodTruckApp.Truck'),
        ),
    ]
